export function renderHelp(unknownCommand?: string): string {
  const unknownCommandBlock = unknownCommand ? `Unknown command: ${unknownCommand}\n\n` : "";

  return `${unknownCommandBlock}PhaseDev AI Framework

Overview:
  PhaseDev is a state-driven agentic engineering flow controller. It stores
  workflow state in the target project under .phasedev/ and prints exact stage
  contracts for AI agents. The controller owns routing, artifact contracts,
  approval gates, validation verdicts, archive state, and allowed state files.

Workflow:
  1. phasedev init-project --project-path <path>
     Create the PhaseDev workspace structure and project config.
  2. phasedev init --project-path <path>
     Print the context-only handshake prompt. This command does not modify files.
  3. phasedev next --project-path <path>
     Print the executable stage contract for the current flow state.
  4. Repeat phasedev next until the change is archived or blocked.

Commands:
  phasedev help
      Print this help. Aliases: phasedev --help, phasedev -h.

  phasedev init-project [--project-path <path>]
      Create .phasedev workspace directories and .phasedev/config.yaml.
      Idempotent: existing directories are reused and an existing config is not overwritten.
      Side effects: writes only under <project-path>/.phasedev/.

  phasedev init [--project-path <path>]
      Print the PhaseDev init handshake prompt.
      Side effects: none. It must not create, read, edit, move, approve, test, or validate files.

  phasedev next [--project-path <path>] [--config <path>]
      Resolve current flow state and print the next executable stage prompt.
      Side effects: may move an archive-ready change into .phasedev/changes/archive/
      before printing the Archive prompt.

  phasedev check [--project-path <path>] [--expect-route <route>] [--expect-stage <stage>]
      Validate current controller route without rendering a stage prompt.
      Side effects: none.

  phasedev check-validation --project-path <path> --scope phase --phase-id <N>
  phasedev check-validation --project-path <path> --scope final
      Validate validation_findings.md completion semantics for phase or final validation.
      Side effects: none.

  phasedev check-archive --archive-path <path>
      Validate completed archive state and optional delta specs.
      Side effects: none.

Options:
  --project-path, -p <path>   Target project path. Defaults to the current directory.
  --config <path>             Explicit PhaseDev config path for next.
  --expect-route <route>      Expected route for check.
  --expect-stage <stage>      Expected stage for check.
  --scope phase|final         Validation scope for check-validation.
  --phase-id <N>              Phase number for phase validation checks.
  --archive-path <path>       Archived change path for check-archive.

Generated files:
  .phasedev/config.yaml
      Project-local PhaseDev configuration. If absent, next falls back to the framework config.
  .phasedev/changes/
      Active change roots. At most one non-archive active change should exist.
  .phasedev/changes/archive/
      Archived completed changes.
  .phasedev/specs/
      Long-lived delta specs generated by Archive for future Research context.
  .phasedev/logs/
      Runner logs when loop logging is enabled.

Stages:
  setup             Create prd.md and rules.md for the active change.
  research          Record source-grounded research_facts.md.
  design            Produce architecture/design.md.
  plan              Produce implementation_plan.md.
  implementation    Execute the current implementation phase.
  phase_validation  Validate the completed phase.
  final_validation  Validate the full change.
  repair            Fix validation findings.
  archive           Move completed flow state to archive and sync delta specs.

Examples:
  phasedev help
  phasedev init-project --project-path /absolute/path/to/project
  phasedev init --project-path /absolute/path/to/project
  phasedev next --project-path /absolute/path/to/project
  phasedev check --project-path /absolute/path/to/project --expect-route setup
  phasedev check-validation --project-path /absolute/path/to/project --scope final
  phasedev check-archive --archive-path /absolute/path/to/project/.phasedev/changes/archive/2026-06-17-my-change
`;
}
